notifications:
  email:
    - mig-travis@cern.ch
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - pip install dirq
  - pip install simplejson || echo "ok"
  - pip install stomp.py || echo "ok"
  - pip install lz4 || echo "ok"
  - pip install pycodestyle
  - pip install pylint
  - curl -O -R -S -f -s https://raw.github.com/cern-mig/dev-tools/master/python/pylint.sh
  - curl -O -R -S -f -s https://raw.github.com/cern-mig/dev-tools/master/python/.pylintrc
# command to run tests
script:
  - pycodestyle messaging test example/*.py
  - sh pylint.sh messaging test example/*.py || echo "*ignored*"
  - python setup.py test
  - python setup.py install
  - python example/generator_example.py
  - python example/message_example.py
  - python example/queue_example.py
