name: Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['2.7', '3.5', '3.6', '3.7', '3.8', '3.9', '3.10']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout dev-tools
        uses: actions/checkout@v2
        with:
          repository: cern-mig/dev-tools
          path: ./dev-tools
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pycodestyle pylint
          pip install dirq
          pip install simplejson || echo "ok"
          pip install stomp.py || echo "ok"
          pip install lz4 || echo "ok"
      - name: Lint with pycodestyle
        run: |
          pycodestyle messaging test example/*.py
      - name: Lint with pylint
        run: |
          pylint --exit-zero --rcfile dev-tools/python/.pylintrc messaging test example/*.py
      - name: Test
        run: |
          python setup.py test
          python setup.py install
          python example/generator_example.py
          python example/message_example.py
          python example/queue_example.py
